# tox Configuration

requires = ["tox>=4"]
env_list = ["3.11"]

[env_run_base]
description = "Run Unit Test"
deps = [
    "pytest>=9.0",
    "pytest-asyncio>=1.3",
    "pytest-cov>=7.0",
    "pytest-mock>=3.15",
]
# commands = [["pytest", "test/", "-k", "TestPlatform and test_create_mock"]]
commands = [["pytest", "test/test_localpath.py"]]
