# python-downloads = "manual"
python-downloads = "never"

[[index]]
name = "pypi"
url = "https://pypi.org/simple"
publish-url = "https://pypi.org"

[[index]]
name = "test-pypi"
url = "https://test.pypi.org/simple"
publish-url = "https://test.pypi.org"
